all :  lab1-2

lab1-2: lab1-2.c GL_utilities.c VectorUtils2.c LoadTGA.c loadobj.c
	gcc -Wall -std=c99 -o lab1-2 -lglut -lGL -DGL_GLEXT_PROTOTYPES lab1-2.c GL_utilities.c VectorUtils2.c LoadTGA.c loadobj.c

clean :
	rm lab1-2

